### ISSUE TITLE
Not working Caddy 0.10.12

### ISSUE THREAD

**Issue by kenits** [linkonoid/caddy-dyndns#1]
Hello.
I'm trying to start the plugin but nothing works, please help me.
I downloaded the caddy using this link `https://caddyserver.com/download/windows/amd64?plugins=dyndns&license=personal`
Caddy version 0.10.12
The plugin appears in the list of installed ones, but when I try to use it the error occurs.
`Error during parsing: Unknown directive 'dyndns'`
Caddyfile taken from here `https://github.com/linkonoid/caddy-dyndns/blob/master/Caddyfile`

**Comment by wxyzh** [comment]
the same problem 
Caddy version 0.11.0

**Comment by hacker1024** [comment]
I have the same problem, Caddy 0.11.0

**Comment by linust** [comment]
To chime in. The issue is still there on Caddy 0.11.1 (not surprising since there are no updates on this repo)

**Comment by linust** [comment]
It seems to me that the "dyndns" plugin needs to be listed here https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/plugin.go to make it work. Note that I have not tested this fix yet, no time to setup environment and checkout code ATM. Am I on the right track @linkonoid?

**Comment by linkonoid** [comment]
Yes, that's right - you need to compile manually, everything is indicated in the install documentation on https://github.com/linkonoid/caddy-dyndns (adding in https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/plugin.go and others addings). Everything is quite trivial.
The plugin is not automated added to the Caddy repository (it must be approved mholt and added to official rpository, although a lot of time has passed).

**Comment by mholt** [comment]
> The plugin is not automated added to the Caddy repository (it must be approved mholt and added to official rpository, although a lot of time has passed).

Hi, it seems there have been no PRs to add the directive to Caddy: https://github.com/mholt/caddy/pulls?utf8=%E2%9C%93&q=is%3Apr+dyndns

**Comment by linkonoid** [comment]
> > The plugin is not automated added to the Caddy repository (it must be approved mholt and added to official rpository, although a lot of time has passed).
> 
> Hi, it seems there have been no PRs to add the directive to Caddy: https://github.com/mholt/caddy/pulls?utf8=%E2%9C%93&q=is%3Apr+dyndns

Hi, Matt! 
I added PR, please confirm the pull merge to close a issue
