### ISSUE TITLE
The plugin needs to be updated to support the Caddy 1.0.0 version

### ISSUE THREAD

**Issue by a11y-guide** [linkonoid/caddy-dyndns#2]
Thanks.
https://caddy.community/t/caddy-1-0-0-beta2-released-and-instructions-for-plugin-developers/5540

**Comment by naiba** [comment]
I don't think this is a problem. Did you check the dydns plugin when you downloaded it from the caddyserver.com/download page?

**Comment by naiba** [comment]
噢哟，活捉熊大一只

**Comment by naiba** [comment]
fixed at #3

**Comment by naiba** [comment]
@linkonoid It seems you should update plugin version. https://github.com/mholt/caddy/wiki/Publishing-a-Plugin-to-the-Download-Page#updating-your-plugin

**Comment by linkonoid** [comment]
> @linkonoid It seems you should update plugin version. https://github.com/mholt/caddy/wiki/Publishing-a-Plugin-to-the-Download-Page#updating-your-plugin

Hi @naiba, we have a problem with the assembly on the official portal, error on "go test" (and locally too on version 1.12.4). Obviously the matter is os.Getenv("..."). This log from portal:

plugin deploy failed
go test github.com/linkonoid/caddy-dyndns@master: exit status 1

..........................................................
2019/05/14 12:24:38 exec [/tmp/buildenv_05-14-1224.532547477/repo] /usr/local/bin/go vet github.com/linkonoid/caddy-dyndns/...
2019/05/14 12:24:49 exec [/tmp/buildenv_05-14-1224.532547477/repo] /usr/local/bin/go test -race github.com/linkonoid/caddy-dyndns/...
--- FAIL: TestDnsupd (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 6 [running]:
testing.tRunner.func1(0xc0000d0100)
	/usr/local/go/src/testing/testing.go:830 +0x69d
panic(0x8a04a0, 0xc13820)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/linkonoid/caddy-dyndns.dnspodupd(0x8ff5d1, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000043c20, 0x1, ...)
	/tmp/buildenv_05-14-1224.532547477/repo/dnspod.go:47 +0x1c6f
github.com/linkonoid/caddy-dyndns.TestDnsupd(0xc0000d0100)
	/tmp/buildenv_05-14-1224.532547477/repo/dnspod_test.go:15 +0x1fb
testing.tRunner(0xc0000d0100, 0x9166f8)
	/usr/local/go/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x65b
FAIL	github.com/linkonoid/caddy-dyndns	0.017s

**Comment by naiba** [comment]
@linkonoid get it, Fixed #5

**Comment by naiba** [comment]
@linkonoid get it, Fixed #5

**Comment by naiba** [comment]
@linkonoid don't forget to deploy a new version and edit description `Dynamic dns plugin for Caddy server (on this moment support cloudflare, yandex and dnspod)` (*^__^*)

**Comment by linkonoid** [comment]
> @linkonoid don't forget to deploy a new version and edit description `Dynamic dns plugin for Caddy server (on this moment support cloudflare, yandex and dnspod)` (_^__^_)

OK
