### ISSUE TITLE
Support for Digital Ocean

### ISSUE THREAD

**Issue by PaluMacil** [linkonoid/caddy-dyndns#6]
Support for Digital Ocean shouldn't be too hard since [they have a Go library](https://github.com/digitalocean/godo) and it's fairly widely used, so I think it would be appreciated.

**Comment by naiba** [comment]
Providing your api_token and domain name, I will test with `test-dyndns.your.domain` to complete it in the next few days.

**Comment by linkonoid** [comment]
Thank @naiba for add support Digital Ocean. Very pleased that people need it. Recently I went to the developer’s account on the official Caddy server and was pleasantly surprised by more than 8000 server compilations using this plugin. Initially, the project was conceived to host a Caddy server on a router with a dynamic IP. In the near futurewill try to add some more new providers. Demand creates supply :)
